// Generated by scripts/build-catalog.mjs from the VaultDB Nest registry. Do not edit by hand.
// Source: github.com/devmchechi/nest-registry (2026-10-09). 21 entries.
window.NEST_CATALOG = {
  "registry": "github.com/devmchechi/nest-registry",
  "registryWebUrl": "https://github.com/devmchechi/nest-registry",
  "source": "live",
  "snapshotDate": "2026-10-09",
  "entries": [
    {
      "kind": "pack",
      "id": "analytics-pack",
      "name": "Analytics Pack",
      "description": "Load and validate CSV/JSON data, chart it honestly, and write a daily KPI report where every number is computed.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "analytics",
        "data",
        "charts",
        "reporting"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-analytics-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [
          "raw.githubusercontent.com"
        ],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.05,
        "max": 0.45
      },
      "license": null,
      "agents": [
        {
          "id": "data-fetcher",
          "name": "Data Fetcher",
          "description": "Loads CSV and JSON data from your working folder or allowlisted URLs, validates and cleans it, and saves tidy datasets plus a data-quality profile for analysis."
        },
        {
          "id": "chart-generator",
          "name": "Chart Generator",
          "description": "Creates clear, honest charts (PNG or SVG) from CSV/JSON data in your working folder, picking the right chart type and labeling everything a reader needs."
        },
        {
          "id": "report-writer",
          "name": "Report Writer",
          "description": "Writes concise metrics reports from your data and charts, with KPIs against targets, notable changes, verified numbers and clear next questions, in Markdown for your team."
        }
      ],
      "workflows": [
        "daily-metrics"
      ],
      "installSizeKb": 30
    },
    {
      "kind": "agent",
      "id": "arxiv-researcher",
      "name": "ArXiv Researcher",
      "description": "Searches arXiv and Semantic Scholar for papers on a topic, ranks them by relevance and impact, and saves a clean shortlist with links and metadata.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "research",
        "papers",
        "arxiv",
        "search"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-research-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [
          "export.arxiv.org",
          "api.semanticscholar.org"
        ],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.01,
        "max": 0.15
      },
      "license": null,
      "path": "agents/arxiv-researcher"
    },
    {
      "kind": "agent",
      "id": "blog-draft-writer",
      "name": "Blog Draft Writer",
      "description": "Turns a topic, outline or rough notes into a well-structured, publish-ready blog draft in your voice, with headline options, meta description and a clear call to action.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "content",
        "writing",
        "blogging",
        "marketing"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-content-pack",
      "capabilities": {
        "tools": [
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.02,
        "max": 0.2
      },
      "license": null,
      "path": "agents/blog-draft-writer"
    },
    {
      "kind": "agent",
      "id": "calendar-summarizer",
      "name": "Calendar Summarizer",
      "description": "Reads exported calendars (.ics or CSV) from your working folder and summarizes your day or week, including conflicts, prep needed, focus time and a daily briefing.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "personal",
        "calendar",
        "productivity",
        "offline"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-personal-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.01,
        "max": 0.1
      },
      "license": null,
      "path": "agents/calendar-summarizer"
    },
    {
      "kind": "agent",
      "id": "chart-generator",
      "name": "Chart Generator",
      "description": "Creates clear, honest charts (PNG or SVG) from CSV/JSON data in your working folder, picking the right chart type and labeling everything a reader needs.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "analytics",
        "charts",
        "visualization"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-analytics-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.01,
        "max": 0.12
      },
      "license": null,
      "path": "agents/chart-generator"
    },
    {
      "kind": "agent",
      "id": "citation-formatter",
      "name": "Citation Formatter",
      "description": "Turns DOIs, arXiv IDs, titles or messy reference lists into verified BibTeX, APA 7 and MLA 9 citations, using Crossref and arXiv metadata.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "research",
        "citations",
        "bibtex",
        "writing"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-research-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [
          "api.crossref.org",
          "export.arxiv.org"
        ],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.01,
        "max": 0.08
      },
      "license": null,
      "path": "agents/citation-formatter"
    },
    {
      "kind": "agent",
      "id": "code-reviewer",
      "name": "Code Reviewer",
      "description": "Reviews a git diff or set of files like a senior engineer, finding real bugs, security issues and risky changes, with file and line references and concrete fixes.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "engineering",
        "code-review",
        "security",
        "git"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-engineering-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "shell"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.02,
        "max": 0.4
      },
      "license": null,
      "path": "agents/code-reviewer"
    },
    {
      "kind": "pack",
      "id": "content-pack",
      "name": "Content Pack",
      "description": "Draft blog posts in your voice, audit them for SEO, and assemble a paste-ready newsletter issue each week.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "content",
        "writing",
        "seo",
        "newsletter"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-content-pack",
      "capabilities": {
        "tools": [
          "read_file",
          "write_file",
          "list_dir",
          "shell"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "write_file",
          "shell"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.06,
        "max": 0.5
      },
      "license": null,
      "agents": [
        {
          "id": "blog-draft-writer",
          "name": "Blog Draft Writer",
          "description": "Turns a topic, outline or rough notes into a well-structured, publish-ready blog draft in your voice, with headline options, meta description and a clear call to action."
        },
        {
          "id": "newsletter-formatter",
          "name": "Newsletter Formatter",
          "description": "Assembles posts, links and announcements into a polished newsletter issue, with subject lines, preview text, Markdown and email-safe HTML ready to paste into your email tool."
        },
        {
          "id": "seo-analyzer",
          "name": "SEO Analyzer",
          "description": "Audits a draft or HTML page for on-page SEO and readability (keyword use, titles, headings, meta, links, structure) and returns a prioritized fix list with rewrites."
        }
      ],
      "workflows": [
        "weekly-content"
      ],
      "installSizeKb": 30
    },
    {
      "kind": "agent",
      "id": "data-fetcher",
      "name": "Data Fetcher",
      "description": "Loads CSV and JSON data from your working folder or allowlisted URLs, validates and cleans it, and saves tidy datasets plus a data-quality profile for analysis.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "analytics",
        "data",
        "csv",
        "etl"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-analytics-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [
          "raw.githubusercontent.com"
        ],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.01,
        "max": 0.12
      },
      "license": null,
      "path": "agents/data-fetcher"
    },
    {
      "kind": "agent",
      "id": "docs-generator",
      "name": "Docs Generator",
      "description": "Writes and updates READMEs, API references, docstrings and changelogs from your actual code, matching your project's voice and never documenting features that don't exist.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "engineering",
        "documentation",
        "writing"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-engineering-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.02,
        "max": 0.4
      },
      "license": null,
      "path": "agents/docs-generator"
    },
    {
      "kind": "agent",
      "id": "email-triager",
      "name": "Email Triager",
      "description": "Sorts exported emails (.eml, .mbox, text) from your working folder into what needs action, replies or reading, and drafts short replies. Fully offline.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "personal",
        "email",
        "productivity",
        "offline"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-personal-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.01,
        "max": 0.2
      },
      "license": null,
      "path": "agents/email-triager"
    },
    {
      "kind": "pack",
      "id": "engineering-pack",
      "name": "Engineering Pack",
      "description": "Review code, write tests, generate docs and summarize pull requests for the git repository in your working folder.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "engineering",
        "code-review",
        "testing",
        "documentation"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-engineering-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "list_dir",
          "write_file"
        ],
        "network": [
          "api.github.com"
        ],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.08,
        "max": 0.9
      },
      "license": null,
      "agents": [
        {
          "id": "code-reviewer",
          "name": "Code Reviewer",
          "description": "Reviews a git diff or set of files like a senior engineer, finding real bugs, security issues and risky changes, with file and line references and concrete fixes."
        },
        {
          "id": "test-writer",
          "name": "Test Writer",
          "description": "Writes focused, idiomatic unit and integration tests for your code using the project's existing framework, runs them when possible, and reports coverage gaps."
        },
        {
          "id": "docs-generator",
          "name": "Docs Generator",
          "description": "Writes and updates READMEs, API references, docstrings and changelogs from your actual code, matching your project's voice and never documenting features that don't exist."
        },
        {
          "id": "pr-summarizer",
          "name": "PR Summarizer",
          "description": "Summarizes a pull request or branch diff into a clear description covering what changed, why, risk, testing and reviewer focus. Works on local repos and public GitHub PRs."
        }
      ],
      "workflows": [
        "pr-review"
      ],
      "installSizeKb": 38
    },
    {
      "kind": "agent",
      "id": "meeting-notes",
      "name": "Meeting Notes",
      "description": "Turns meeting transcripts or rough notes from your working folder into clean minutes with decisions, owners, due dates and a follow-up email draft.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "personal",
        "meetings",
        "notes",
        "productivity",
        "offline"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-personal-pack",
      "capabilities": {
        "tools": [
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.01,
        "max": 0.12
      },
      "license": null,
      "path": "agents/meeting-notes"
    },
    {
      "kind": "agent",
      "id": "newsletter-formatter",
      "name": "Newsletter Formatter",
      "description": "Assembles posts, links and announcements into a polished newsletter issue, with subject lines, preview text, Markdown and email-safe HTML ready to paste into your email tool.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "content",
        "newsletter",
        "email",
        "marketing"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-content-pack",
      "capabilities": {
        "tools": [
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.01,
        "max": 0.12
      },
      "license": null,
      "path": "agents/newsletter-formatter"
    },
    {
      "kind": "agent",
      "id": "paper-summarizer",
      "name": "Paper Summarizer",
      "description": "Reads research papers (PDF, text, or abstracts) from your working folder and writes structured, faithful summaries with methods, results, limitations and takeaways.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "research",
        "papers",
        "summaries",
        "pdf"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-research-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.02,
        "max": 0.3
      },
      "license": null,
      "path": "agents/paper-summarizer"
    },
    {
      "kind": "pack",
      "id": "personal-pack",
      "name": "Personal Pack",
      "description": "Offline email triage, calendar summaries and meeting minutes from files you export, combined into a daily briefing.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "personal",
        "productivity",
        "email",
        "calendar",
        "offline"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-personal-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.04,
        "max": 0.4
      },
      "license": null,
      "agents": [
        {
          "id": "email-triager",
          "name": "Email Triager",
          "description": "Sorts exported emails (.eml, .mbox, text) from your working folder into what needs action, replies or reading, and drafts short replies. Fully offline."
        },
        {
          "id": "calendar-summarizer",
          "name": "Calendar Summarizer",
          "description": "Reads exported calendars (.ics or CSV) from your working folder and summarizes your day or week, including conflicts, prep needed, focus time and a daily briefing."
        },
        {
          "id": "meeting-notes",
          "name": "Meeting Notes",
          "description": "Turns meeting transcripts or rough notes from your working folder into clean minutes with decisions, owners, due dates and a follow-up email draft."
        }
      ],
      "workflows": [
        "daily-briefing"
      ],
      "installSizeKb": 31
    },
    {
      "kind": "agent",
      "id": "pr-summarizer",
      "name": "PR Summarizer",
      "description": "Summarizes a pull request or branch diff into a clear description covering what changed, why, risk, testing and reviewer focus. Works on local repos and public GitHub PRs.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "engineering",
        "pull-requests",
        "git",
        "github"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-engineering-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "list_dir"
        ],
        "network": [
          "api.github.com"
        ],
        "pilots": [],
        "requiresApproval": [
          "shell"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.01,
        "max": 0.15
      },
      "license": null,
      "path": "agents/pr-summarizer"
    },
    {
      "kind": "agent",
      "id": "report-writer",
      "name": "Report Writer",
      "description": "Writes concise metrics reports from your data and charts, with KPIs against targets, notable changes, verified numbers and clear next questions, in Markdown for your team.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "analytics",
        "reporting",
        "kpis"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-analytics-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.02,
        "max": 0.18
      },
      "license": null,
      "path": "agents/report-writer"
    },
    {
      "kind": "pack",
      "id": "research-pack",
      "name": "Research Pack",
      "description": "Search arXiv and Semantic Scholar, summarize papers faithfully, and produce verified citations, chained into a literature review.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "research",
        "papers",
        "citations",
        "academic"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-research-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [
          "export.arxiv.org",
          "api.semanticscholar.org",
          "api.crossref.org"
        ],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.05,
        "max": 0.6
      },
      "license": null,
      "agents": [
        {
          "id": "arxiv-researcher",
          "name": "ArXiv Researcher",
          "description": "Searches arXiv and Semantic Scholar for papers on a topic, ranks them by relevance and impact, and saves a clean shortlist with links and metadata."
        },
        {
          "id": "paper-summarizer",
          "name": "Paper Summarizer",
          "description": "Reads research papers (PDF, text, or abstracts) from your working folder and writes structured, faithful summaries with methods, results, limitations and takeaways."
        },
        {
          "id": "citation-formatter",
          "name": "Citation Formatter",
          "description": "Turns DOIs, arXiv IDs, titles or messy reference lists into verified BibTeX, APA 7 and MLA 9 citations, using Crossref and arXiv metadata."
        }
      ],
      "workflows": [
        "literature-review"
      ],
      "installSizeKb": 32
    },
    {
      "kind": "agent",
      "id": "seo-analyzer",
      "name": "SEO Analyzer",
      "description": "Audits a draft or HTML page for on-page SEO and readability (keyword use, titles, headings, meta, links, structure) and returns a prioritized fix list with rewrites.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "content",
        "seo",
        "marketing",
        "audit"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-content-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "shell"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.01,
        "max": 0.1
      },
      "license": null,
      "path": "agents/seo-analyzer"
    },
    {
      "kind": "agent",
      "id": "test-writer",
      "name": "Test Writer",
      "description": "Writes focused, idiomatic unit and integration tests for your code using the project's existing framework, runs them when possible, and reports coverage gaps.",
      "publisher": "devmchechi",
      "publisherName": "devmchechi",
      "verified": true,
      "version": "1.0.0",
      "minNestVersion": "0.1.0",
      "tags": [
        "engineering",
        "testing",
        "quality"
      ],
      "repoUrl": "https://github.com/devmchechi/nest-engineering-pack",
      "capabilities": {
        "tools": [
          "shell",
          "read_file",
          "write_file",
          "list_dir"
        ],
        "network": [],
        "pilots": [],
        "requiresApproval": [
          "shell",
          "write_file"
        ],
        "aws": []
      },
      "estimatedCostUsd": {
        "min": 0.03,
        "max": 0.5
      },
      "license": null,
      "path": "agents/test-writer"
    }
  ]
};
