name: deploy vaultdb.ai

on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 2 * * *"
  repository_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '**'
    paths-ignore:
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  Deploy:
    name: Deploy VaultDB.ai
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build distribtion
        shell: bash
        run: |
            mkdir -p dist
            cp ./*.html ./dist/
            cp -r ./css ./dist/
            cp -r ./img ./dist/
            cp -r ./js ./dist/
            [ -d ./marketplace ] && cp -r ./marketplace ./dist/
            [ -d ./database ] && cp -r ./database ./dist/
            [ -d ./docs ] && cp -r ./docs ./dist/
            [ -d ./products ] && cp -r ./products ./dist/

      - name: Sync to S3
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 sync ./dist/ s3://${{ secrets.AWS_BUCKET }}/ --delete
