name: Upload Cloudformation templates & deploy for preview

on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 2 * * *"
  repository_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '**'
    paths-ignore:
      - 'examples/**'
      - 'test/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  Deploy:
    name: Deploy Vaultdb Analytics and Datalake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build distribtion
        shell: bash
        run: |
            mkdir -p dist
            cp ./*.html ./dist/
            cp ./README.md ./dist/
            cp -r ./css ./dist/          
            cp -r ./img ./dist/          
            cp -r ./js ./dist/          

      - uses: vitorsgomes/s3-rm-action@master
        name: cleanup s3 folder awsquickstart
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PATH_TO_DELETE: '/'

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.S3_ID }}
          aws_secret_access_key: ${{ secrets.S3_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist'
          destination_dir: ''
